# Generated by Django 5.1.1 on 2024-10-02 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_account_user_account_user_id_alter_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='user',
        ),
        migrations.AddField(
            model_name='credential',
            name='user_id',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credential',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
