# Generated by Django 5.1.1 on 2024-10-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_credential_user_credential_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
